### ISSUE TITLE
media-video/bomi Libav option 

### ISSUE THREAD

**Issue by necrose99** [sandikata/ROKO__#10]
https://plus.google.com/+mohamedamineBahayou/posts/CLjSJYQATZs

request to add https://wiki.gentoo.org/wiki/Libav to media-video/bomi as so as to not pull in ffmpeg 

ffmpeg on sabayon Linux breaks stuff .
if this is possible thank you..

**Comment by AsukaLangleyfag** [comment]
Unfortunately it's not possible to use bomi with libav.

**Comment by sandikata** [comment]
thread should be closed because bomi doesn't work with libav. And i don't support it anymore. Sorry.
