### ISSUE TITLE
Couldn't download 'live.2015.05.03.tar.gz'. Aborting

### ISSUE THREAD

**Issue by pashosh** [sandikata/ROKO__#11]
> > > Downloading 'http://mirror.isoc.org.il/pub/gentoo/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:33--  http://mirror.isoc.org.il/pub/gentoo/distfiles/live.2015.05.03.tar.gz
> > > Resolving mirror.isoc.org.il... 192.115.211.70
> > > Connecting to mirror.isoc.org.il|192.115.211.70|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:33 ERROR 404: Not Found.
> > > 
> > > Downloading 'ftp://mirror.isoc.org.il/gentoo/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:33--  ftp://mirror.isoc.org.il/gentoo/distfiles/live.2015.05.03.tar.gz
> > >            => ‘/usr/portage/distfiles/live.2015.05.03.tar.gz’
> > > Resolving mirror.isoc.org.il... 192.115.211.70
> > > Connecting to mirror.isoc.org.il|192.115.211.70|:21... connected.
> > > Logging in as anonymous ... Logged in!
> > > ==> SYST ... done.    ==> PWD ... done.
> > > ==> TYPE I ... done.  ==> CWD (1) /gentoo/distfiles ... done.
> > > ==> SIZE live.2015.05.03.tar.gz ... done.

==> PASV ... done.    ==> RETR live.2015.05.03.tar.gz ... 
No such file ‘live.2015.05.03.tar.gz’.

> > > Downloading 'http://files.gentoo.gr/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:34--  http://files.gentoo.gr/distfiles/live.2015.05.03.tar.gz
> > > Resolving files.gentoo.gr... 62.38.102.66
> > > Connecting to files.gentoo.gr|62.38.102.66|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:34 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://ftp.ntua.gr/pub/linux/gentoo/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:34--  http://ftp.ntua.gr/pub/linux/gentoo/distfiles/live.2015.05.03.tar.gz
> > > Resolving ftp.ntua.gr... 147.102.222.211
> > > Connecting to ftp.ntua.gr|147.102.222.211|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:34 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://de-mirror.org/gentoo/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:34--  http://de-mirror.org/gentoo/distfiles/live.2015.05.03.tar.gz
> > > Resolving de-mirror.org... 195.20.242.90, 2001:8d8:580:400::c314:f25a
> > > Connecting to de-mirror.org|195.20.242.90|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:34 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://gentoo.inode.at/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:34--  http://gentoo.inode.at/distfiles/live.2015.05.03.tar.gz
> > > Resolving gentoo.inode.at... 81.223.20.162
> > > Connecting to gentoo.inode.at|81.223.20.162|:80... connected.
> > > HTTP request sent, awaiting response... 301 Moved Permanently
> > > Location: http://gentoo.mirror.dkm.cz/pub/gentoo/distfiles/live.2015.05.03.tar.gz [following]
> > > --2015-08-18 17:46:35--  http://gentoo.mirror.dkm.cz/pub/gentoo/distfiles/live.2015.05.03.tar.gz
> > > Resolving gentoo.mirror.dkm.cz... 86.49.49.49, 2a02:8300:8000:3::49
> > > Connecting to gentoo.mirror.dkm.cz|86.49.49.49|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:35 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://ftp.halifax.rwth-aachen.de/gentoo/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:35--  http://ftp.halifax.rwth-aachen.de/gentoo/distfiles/live.2015.05.03.tar.gz
> > > Resolving ftp.halifax.rwth-aachen.de... 137.226.34.42
> > > Connecting to ftp.halifax.rwth-aachen.de|137.226.34.42|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:35 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://gentoo.osuosl.org/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:35--  http://gentoo.osuosl.org/distfiles/live.2015.05.03.tar.gz
> > > Resolving gentoo.osuosl.org... 140.211.166.134
> > > Connecting to gentoo.osuosl.org|140.211.166.134|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:36 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://gentoo.ussg.indiana.edu/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:36--  http://gentoo.ussg.indiana.edu/distfiles/live.2015.05.03.tar.gz
> > > Resolving gentoo.ussg.indiana.edu... 156.56.247.195
> > > Connecting to gentoo.ussg.indiana.edu|156.56.247.195|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:36 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://gentoo-distfiles.mirrors.tds.net/distfiles/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:36--  http://gentoo-distfiles.mirrors.tds.net/distfiles/live.2015.05.03.tar.gz
> > > Resolving gentoo-distfiles.mirrors.tds.net... 216.165.129.135
> > > Connecting to gentoo-distfiles.mirrors.tds.net|216.165.129.135|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:36 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://www.live555.com/liveMedia/public/live.2015.05.03.tar.gz'
> > > --2015-08-18 17:46:36--  http://www.live555.com/liveMedia/public/live.2015.05.03.tar.gz
> > > Resolving www.live555.com... 4.79.217.242
> > > Connecting to www.live555.com|4.79.217.242|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2015-08-18 17:46:37 ERROR 404: Not Found.

!!! Couldn't download 'live.2015.05.03.tar.gz'. Aborting.
[31;01m \* [39;49;00mFetch failed for 'media-plugins/live-2015.05.03', Log file:
[31;01m \* [39;49;00m '/var/log/portage/media-plugins:live-2015.05.03:20150818-144632.log'

**Comment by sandikata** [comment]
sorry for that gentoo team allready do ebuild with recent versions so this one will be removed from my repo.
