### ISSUE TITLE
some digests are missing

### ISSUE THREAD

**Issue by alexdux** [sandikata/ROKO__#12]
- Missing digest for '/var/lib/layman/ROKO__/media-plugins/deadbeef-bs2b/deadbeef-bs2b-20110319.ebuild'
  emerge: search: aux_get('media-plugins/deadbeef-bs2b-20110319') failed, skipping
- Missing digest for '/var/lib/layman/ROKO__/media-plugins/deadbeef-gnome-mmkeys/deadbeef-gnome-mmkeys-20131012.ebuild'
  emerge: search: aux_get('media-plugins/deadbeef-gnome-mmkeys-20131012') failed, skipping
- Missing digest for '/var/lib/layman/ROKO__/media-plugins/deadbeef-jack/deadbeef-jack-20110321.ebuild'
  emerge: search: aux_get('media-plugins/deadbeef-jack-20110321') failed, skipping
- Missing digest for '/var/lib/layman/ROKO__/media-plugins/deadbeef-opus/deadbeef-opus-0.6.ebuild'
  emerge: search: aux_get('media-plugins/deadbeef-opus-0.6') failed, skipping

**Comment by sandikata** [comment]
i fix them.
