### ISSUE TITLE
some bad substitution @viber NEEDED.ELF.2

### ISSUE THREAD

**Issue by alexdux** [sandikata/ROKO__#13]
```
emerge -p @preserved-rebuild
...
/var/db/pkg/net-im/viber-9999-r9999/NEEDED.ELF.2: $: bad substitution
```

probably line:
X86_64;/opt/viber/Viber;;$ORIGIN:$$ORIGIN:/Jenkins/jobs/Linux-4-2-1-Qt5.2-b.............

**Comment by sandikata** [comment]
i dont have idea of viber its blob. so i think to remove it for now. It doesnt work on gentoo at all. It segfault when you try to call somebody.

**Comment by alexdux** [comment]
Oh, no. Don't remove it - it works fine (for me). No segfault at all.
I'll try to discover the issue...

**Comment by sandikata** [comment]
well i will readd it again..

**Comment by alexdux** [comment]
Hi. I added a new Viber blob to my own overlay. (The old one is not working any more) No more request for Viber ebuild. Thanks.

**Comment by sandikata** [comment]
so is it works on gentoo for calling ?

**Comment by alexdux** [comment]
Free calling? yes it works (at least for me)...
