### ISSUE TITLE
qt-telegram-staic 5.6.0 version bump

### ISSUE THREAD

**Issue by eegorov** [sandikata/ROKO__#16]
Hello. I like see your ebuild for net-im/telegram with separatly building qt-telegram-static. Now telegram updated to 0.9.49. That not built with qt-5.5.1. I try to update your ebuild 5.5.1 to 5.6.0, but I could not.
Can your bump qt-telegram-static to 5.6.0 please? I, in turn, agree to follow the Telegram and update the ebuild for it as needed. I have already made the first pull reguest for easier assembly it under Gentoo. https://github.com/telegramdesktop/tdesktop/pull/1988 
In order two requests too.

**Comment by sandikata** [comment]
Hello at the moment i am far away from home. And i don't have gentoo machine. Would be insane to install it on notebook. So wait or fix it and send pull request.

**Comment by eegorov** [comment]
Ok. Thanks for answer.

**Comment by sandikata** [comment]
Okay i have updated packages you can enjoy new telegram versions.
С Уважение.

**Comment by sandikata** [comment]
Due to lack of support from author of this package it was removed from repository.
There is already an official package in gentoo portage.
