### ISSUE TITLE
net-p2p/sopcast-player-0.7.4-r1 does not install

### ISSUE THREAD

**Issue by maneamarius** [sandikata/ROKO__#17]
Hi,

I am trying to install net-p2p/sopcast-player-0.7.4-r1 from ROKO__ overlay but it fails to download the file sopcast-player-0.7.4-r1.tar.xz

Are you able to help please?
See the emerge log below.

thanks a lot,
-Marius

> > > Emerging (1 of 1) net-p2p/sopcast-player-0.7.4-r1::ROKO__
> > > Downloading 'http://distfiles.gentoo.org/distfiles/sopcast-player-0.7.4-r1.tar.xz'
> > > --2016-06-11 10:08:59--  http://distfiles.gentoo.org/distfiles/sopcast-player-0.7.4-r1.tar.xz
> > > Resolving distfiles.gentoo.org... 216.165.129.135, 140.211.166.134, 64.50.233.100, ...
> > > Connecting to distfiles.gentoo.org|216.165.129.135|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2016-06-11 10:08:59 ERROR 404: Not Found.
> > > 
> > > Downloading 'ftp://calculate-linuxmaniac.tk/pub/downloads/sopcast-player-0.7.4-r1.tar.xz'
> > > --2016-06-11 10:08:59--  ftp://calculate-linuxmaniac.tk/pub/downloads/sopcast-player-0.7.4-r1.tar.xz
> > >            => ���/usr/portage/distfiles/sopcast-player-0.7.4-r1.tar.xz���
> > > Resolving calculate-linuxmaniac.tk... 195.20.44.113
> > > Connecting to calculate-linuxmaniac.tk|195.20.44.113|:21... failed: Connection timed out.
> > > Retrying.

--2016-06-11 10:10:00--  ftp://calculate-linuxmaniac.tk/pub/downloads/sopcast-player-0.7.4-r1.tar.xz
  (try: 2) => ���/usr/portage/distfiles/sopcast-player-0.7.4-r1.tar.xz���
Connecting to calculate-linuxmaniac.tk|195.20.44.113|:21... failed: Connection timed out.
Retrying.

--2016-06-11 10:11:02--  ftp://calculate-linuxmaniac.tk/pub/downloads/sopcast-player-0.7.4-r1.tar.xz
  (try: 3) => ���/usr/portage/distfiles/sopcast-player-0.7.4-r1.tar.xz���
Connecting to calculate-linuxmaniac.tk|195.20.44.113|:21... failed: Connection timed out.
Giving up.

**Comment by sandikata** [comment]
From long time i do not support this package. Because is too old for new systems and it's hard to make it work.

**Comment by maneamarius** [comment]
Understood.
Can you recommend a replacement for this program so I can watch sopcast channels on linux? What program are you using (if any)?

thanks!
