### ISSUE TITLE
=dev-libs/libgcrypt-1.5.4-r100 is not available in portage now

### ISSUE THREAD

**Issue by blow05** [sandikata/ROKO__#20]
Please bump libgcrypt version.

**Comment by sandikata** [comment]
This version was hardcoded only in acestream packages, which are not maintained by its author anymore, they have switched to noxbit.
There will be unexpected delay for bugfixes. So stay in touch.

**Comment by sandikata** [comment]
This version is available in portage as i can see, so closing this report.
