### ISSUE TITLE
app-shells/zsh-autosuggestions emerge failed

### ISSUE THREAD

**Issue by Universebenzene** [sandikata/ROKO__#21]
Here are my output of `emerge --info '=app-shells/zsh-autosuggestions-9999::ROKO__'` and the build log. Is this my own problem? 
https://pastebin.com/GpmAXCJ6
https://pastebin.com/U21SCKDm

**Comment by sandikata** [comment]
Hello! There will be unexpected delay in fixing issues.
So stay in touch.

**Comment by sandikata** [comment]
fixed
