### ISSUE TITLE
sys-kernel/cachyos-sources: files/config-x86_64-bore fails verification

### ISSUE THREAD

**Issue by ayreonaut-0x** [sandikata/ROKO__#28]
!!! Digest verification failed:
!!! /var/db/repos/ROKO__/sys-kernel/cachyos-sources/files/config-x86_64-bore
!!! Reason: Failed on BLAKE2B verification
!!! Got: a79fd8fd2df72066e8b6ea7bfd820e77e08b7358957a65106f9233aeca8a4eeb7279839283084f53f5e91c45cf7328f835782f84da1f483dcb839b21e8943cc0
!!! Expected: 82d0a02d612fa6bd33444ba8b2ae47d5ba9fbefa2a98b0dd4a21b5343ad0a7f104a20b441e001ea36c7b0e8e4c61a1020a866daf368cbf986f3b1f76baed9af7

**Comment by sandikata** [comment]
Hello, have you synced the repo?

**Comment by ayreonaut-0x** [comment]
Had just added your repository using eselect and done an emaint sync -r ROKO__ and was up to date (https://github.com/sandikata/ROKO__/commit/44f44ae4834f385d8f2b6eab0b0225f6d7d2010c) but this error was still occurring.
Latest commit has fixed the issue. Cheers!
