### ISSUE TITLE
media-video/obs-studio-28.0.1 fails to build: Could NOT find Libv4l2

### ISSUE THREAD

**Issue by kostadinsh** [sandikata/ROKO__#29]
-- OBS:  ENABLED    linux-capture
-- OBS:  ENABLED    linux-pulseaudio
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Libv4l2 (missing: V4L2_LIB V4L2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLibv4l2.cmake:23 (find_package_handle_standard_args)
  plugins/linux-v4l2/CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
[emerge --info.txt](https://github.com/sandikata/ROKO__/files/9791803/emerge.--info.txt)
[buildlog.txt](https://github.com/sandikata/ROKO__/files/9791804/buildlog.txt)

**Comment by sandikata** [comment]
Try to install media-video/obs-v4l2sink

**Comment by kostadinsh** [comment]
Стига по-далече с media-libs/libv4l, ама пита за libvlc, според мен трябва да се преструктурират -DDISABLE флаговете, които се изпращат към CMake, защото изобщо не трябва да ме пита за тези неща, ако USE флаговете не са зададени.

[build.log](https://github.com/sandikata/ROKO__/files/9795368/build.log)

**Comment by sandikata** [comment]
То е много ранен. Едва го подкарах изобщо да се компилира, и то за да ползваш примерно vaapi ускорение (каквато е моята цел, понеже съм приложил patch за AMD HEVC то ти трябва и vlc)

**Comment by kostadinsh** [comment]
Промених ebuilda малко, но не мога да тествам AMD HEVC пача, тъй като не работи на моето поколение видео карти - polaris. Прикачвам го за тестване.

[obs-studio-28.0.1.txt](https://github.com/sandikata/ROKO__/files/9844020/obs-studio-28.0.1.txt)

**Comment by sandikata** [comment]
На единия компютър и аз съм с Polaris10 но работеше доколкото помня, сега с Navi22 също работи.

**Comment by sandikata** [comment]
obs 28.1 е наличен от gentoo хранилището.
