### ISSUE TITLE
CachyOS 6.3.0 Broken with BORE Use Flag

### ISSUE THREAD

**Issue by acjones8** [sandikata/ROKO__#34]
Hello! I was interested in giving BORE a try again now that it's incorporating some of EEVDF, but I noticed that the patch is currently broken on 6.3:

`>>> Unpacking source...`
`>>> Unpacking linux-6.3.tar.xz to /var/tmp/portage/sys-kernel/cachyos-sources-6.3.0/work`
`>>> Source unpacked in /var/tmp/portage/sys-kernel/cachyos-sources-6.3.0/work`
`>>> Preparing source in /var/tmp/portage/sys-kernel/cachyos-sources-6.3.0/work/linux-6.3.0-cachyos ...`
` * Applying 6.3-cachyos-base-all.patch ...                                                                 [ ok ]`
` * Applying 6.3-latency-fix.patch ...                                                                      [ ok ]`
` * Applying 6.3-bore-cachy.patch ...`
`patching file include/linux/sched.h`
`Hunk #1 succeeded at 556 (offset 1 line).`
`Hunk #2 succeeded at 996 (offset 4 lines).`
`patching file init/Kconfig`
`patching file kernel/sched/core.c`
`Hunk #1 succeeded at 4423 (offset 5 lines).`
`Hunk #2 succeeded at 4472 with fuzz 2 (offset 5 lines).`
`Hunk #3 succeeded at 4701 (offset 6 lines).`
`Hunk #4 succeeded at 9200 (offset 35 lines).`
`Hunk #5 succeeded at 9871 (offset 35 lines).`
`patching file kernel/sched/debug.c`
`patching file kernel/sched/fair.c`
`Hunk #4 succeeded at 1046 (offset 78 lines).`
`Hunk #5 succeeded at 1116 (offset 78 lines).`
`Hunk #6 succeeded at 5210 (offset 71 lines).`
`Hunk #7 succeeded at 5256 (offset 71 lines).`
`Hunk #8 succeeded at 6571 (offset 78 lines).`
`Hunk #9 succeeded at 8043 with fuzz 1 (offset 85 lines).`
`Hunk #10 FAILED at 7971.`
`Hunk #11 succeeded at 8173 (offset 98 lines).`
`Hunk #12 succeeded at 8414 (offset 98 lines).`
`1 out of 12 hunks FAILED -- saving rejects to file kernel/sched/fair.c.rej`
`patching file kernel/sched/features.h                                                                      [ !! ]`
 `* ERROR: sys-kernel/cachyos-sources-6.3.0::ROKO__ failed (prepare phase):`
 `*   patch -p1  failed with /var/tmp/portage/sys-kernel/cachyos-sources-6.3.0/files/6.3/6.3-bore-cachy.patch`
 `* `
 `* Call stack:`
 `*               ebuild.sh, line  136:  Called src_prepare`
 `*             environment, line 2802:  Called eapply '/var/tmp/portage/sys-kernel/cachyos-sources-6.3.0/files/6.3/6.3-bore-cachy.patch'`
` *             environment, line 1627:  Called _eapply_patch '/var/tmp/portage/sys-kernel/cachyos-sources-6.3.0/files/6.3/6.3-bore-cachy.patch'`
` *             environment, line 1565:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/sys-kernel/cachyos-sources-6.3.0/files/6.3/6.3-bore-cachy.patch'`
` *   isolated-functions.sh, line  112:  Called die`
` * The specific snippet of code:`
` *              die "$@"`

**Comment by sandikata** [comment]
Hello,

Honestly, I haven't tested with bore.
But default eevdf works fine.

Maybe we have to wait for upstream update.

Regards,
Rosen Aleksandrov

**Comment by acjones8** [comment]
Okay, then I'll try the default EEVDF version and see if maybe I can track down what the issue is later. Thanks for the prompt response, and for your work maintaining this repo!

**Comment by sandikata** [comment]
Thanks,

It is a big effort to keep it updated and well maintained, 10 years+ of hard work.
