### ISSUE TITLE
sys-kernel/cachyos-sources need update

### ISSUE THREAD

**Issue by xz-dev** [sandikata/ROKO__#39]
The [6.5.6-1](https://github.com/CachyOS/linux-cachyos/commit/6150aa9930a480db408f1844396a05b30a037d56) was been released(we can see in [there repo](https://mirror.cachyos.org/repo/x86_64/cachyos/)), anyone can help update it?
I do not know if there are released [6.5.7-1](https://github.com/CachyOS/linux-cachyos/commit/f220b40d5dbd590875cd8103bedd667341ed0b17) version, [seems it's](https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos-bore/.SRCINFO) but no pkg in there repo.
I want to make a PR, But I do not know
If anyone can make a new PR for new version, then we can left more info to let others know how to update next time.
Thanks a lot

-- 2023/10/14 --
Seems cachyos had released 6.5.7(1&2) at there repo, but seems not so stable, it's wait them done the job.

**Comment by sandikata** [comment]
Hello,

I am not aware of cachyos development. My repo is gentoo related. 
I will push new versions. But right now i feel 6.5.5 really stable (for some reason, since 6.1 any .5 versions were the best in my opinion).

**Comment by xz-dev** [comment]
Thanks for the explanation, .5 versions What an amazing meme.
And I find the latest version is 6.6.0rc6-1, but it's a rc version, so maybe we should skip it.

**Comment by sandikata** [comment]
Version 6.5.7 pushed.
I plan to stay away from 6.6 for now.

**Comment by xz-dev** [comment]
I had test new version, and it's work
Thanks again
