### ISSUE TITLE
Soundux needs webkit-gtk 4 slot

### ISSUE THREAD

**Issue by Username404-59** [sandikata/ROKO__#43]
If webkit-gtk 4 isn't installed, emerging the ebuild works but nothing's actually installed, because of this error:
```
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:634 (message):
  The following required packages were not found:

   - webkit2gtk-4.0

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:862 (_pkg_check_modules_internal)
  src/ui/impl/webview/lib/webviewpp/CMakeLists.txt:33 (pkg_check_modules)
```

**Comment by sandikata** [comment]
This application hasn't been updated since 2021, maybe it's better to use flatpak version.

**Comment by Username404-59** [comment]
> This application hasn't been updated since 2021, maybe it's better to use flatpak version.

It's going through a rewrite
