### ISSUE TITLE
fix deps to acestream-player-data and acestream-plugin

### ISSUE THREAD

**Issue by ilya84** [sandikata/ROKO__#7]
I have three fix for two ebuilds:
1. Some time ago Gentoo developers decided to use libav instead of ffmpeg as default media coder. This causes conflicts emerging acestream at new fresh gentoo installations with default USE 'libav'. But my experiments shows that acestream works great on libav with default USE-flags.
2. Dependency =dev-libs/libgcrypt-1.5.4-r100 causes unresolved block with newer ebuild dev-libs/libgcrypt-1.5.4-r1. I don't see any reasons for emerge older ebuild instead of newer.

Diff for media-video/acestream-player-data/acestream-player-data-3.0.2.ebuild :

```
45c45
<       media-video/acestream-ffmpeg[jack=,aac=,modplug=,ieee1394=,speex=,theora=,v4l=,vaapi=,vorbis=,alsa]

---
>       || ( media-video/acestream-ffmpeg[jack=,aac=,modplug=,ieee1394=,speex=,theora=,v4l=,vaapi=,vorbis=,alsa] >=media-video/libav-9.17 )
59c59
<       =dev-libs/libgcrypt-1.5.4-r100

---
>       >=dev-libs/libgcrypt-1.5.4-r1
```

And the last:
I (and think not only I) emerged www-client/firefox-bin instead of www-client/firefox. Fixed deps in www-plugins/acestream-plugin/acestream-plugin-3.0.2.ebuild looks like this:

```
22c22
<   >=www-client/firefox-29.0.99"

---
>   || ( >=www-client/firefox-29.0.99 >=www-client/firefox-bin-29.0.99 )"
```

**Comment by sandikata** [comment]
so make pull request i will review it.

**Comment by sandikata** [comment]
Я не нашел неполадки. Относно libgcrypt я просто занимался с других дела.
Было нужно допилить новая версия acestream и разные версии ffmpeg. И просто не посмотрел нужен ли еще старой gcrypt. Спасибо за доклад!
